version: "3.9"

services:
  web:
    build:
      context: .
    command: python src/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      DJANGO_DEBUG: "True"
      DJANGO_SECRET_KEY: "local-dev-secret"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,0.0.0.0"
      DATABASE_URL: "postgres://examboard:examboard@db:5432/examboard"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: examboard
      POSTGRES_USER: examboard
      POSTGRES_PASSWORD: examboard
      TZ: UTC
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: redis-server --save ""
    profiles: ["cache"]
    ports:
      - "6379:6379"

volumes:
  postgres-data:
